### ISSUE TITLE
sw.js harusnya tidak ada jika asset dan offline page == disable

### ISSUE THREAD

**Issue by todiadiyatmo** [tonjoo/pwa-optimizer#10]
![image](https://user-images.githubusercontent.com/2767210/38846025-6d54ad0e-4224-11e8-92bf-874484fb06ff.png)

Kondisi sekarang kalau asset = disable dan offline_page = disable. harusnya jika asset dan offline_page disable sw.js tidak ada (dan tidak memanggil sw.js)

**Comment by ebenhaezerbm** [comment]
@todiadiyatmo sw.js emang kepanggil kalo salah satunya (offline mode/assets) akitf kok mas, cuma file nya gak di hapus ...
`inc/pwa.class.php`

**Comment by todiadiyatmo** [comment]
- http://caritemanmakan.hipwee.com/sw.js masih terpanggil ketika asset dan offline page kondisi disable
