### ISSUE TITLE
Add Versioning Function on Manifest.json, sw.js, offline-page.html

### ISSUE THREAD

**Issue by iqbaljayadi** [tonjoo/pwa-optimizer#18]
manifest.json, sw.js, dan offline-page.html suka nyangkut sehingga menyulitkan verifikasi PWA ataupun update setting manifest add to homescreen.

Idenya mirip seperti "clear cache" button pada plugin cache, jika di-klik maka url akan ditambahkan query string yang versinya akan berubah/nambah tiap melakukan clear cache.

Atau, setiap melakukan penyimpanan setting PWA, maka versinya ter-update.

**Comment by todiadiyatmo** [comment]
1. source code PWA uda dicek belum ?
2. untuk manifest.json ini adalah file dan bukan route , jadi ga bakal bisa dikasih query param karena yang direquest chrome / browser adalah path file nya
3. dicek setting server apakah ada cache file2 lain

**Comment by todiadiyatmo** [comment]
@iqbaljayadi irnanto sapa namanya tak mention gabisa

**Comment by irnanto27** [comment]
1. sudah mas
2. di basic.hellosehat.com pakai plugin w3tc yg memungkinkan membuat query stryng seperti `https://basic.hellosehat.com/manifest.json?x33262`, tetapi ini lebih bagus jika dibuat versi jg agar jika setting plugin pwa di update maka akan terdeteksi data file tersebut yang terbaru
3. ok saya cek dl mas

**Comment by iqbaljayadi** [comment]
Problemnya bukan di versioningnya, tapi antara dibuatkan fungsi yg ngecek update service worker atau dibiarkan begitu saja. Untuk development-nya, pastikan "reload on refresh" dicentang. Aku tutup issue ini
