### ISSUE TITLE
sw.js & manifest.json berbeda antara server dan browser

### ISSUE THREAD

**Issue by irnanto27** [tonjoo/pwa-optimizer#23]
**Percobaan Di local :** 
1. Update plugin pwa (add to home screen & offline mode)
2. cek file sw.js dan manifest.json _berubah_ lewat editor text / file manager
3. coba jalankan di browser 
- file sw.js di browser belum terupdate / masih ngecache
- file manifest.json di browser belum terupdate / masih ngecache
4. centang `update on reload` & hard refresh atau klik update
5. buka halaman di tab baru 
- file sw.js di browser terupdate sesuai dengan isi file di server
- file manifest.json di browser belum terupdate / masih ngecache
6. cek di incognito
- file sw.js di browser terupdate sesuai dengan isi file di server
- file manifest.json di browser berubah

**Percobaan di server basic :** 
1. Update plugin pwa (add to home screen & offline mode)
2. cek file sw.js dan manifest.json _berubah_ lewat editor text / file manager
3. coba jalankan di browser
- file sw.js di browser belum terupdate / masih ngecache
- file manifest.json di browser belum terupdate / masih ngecache
4. centang `update on reload` & hard refresh atau klik update
5. buka halaman di tab baru 
- file sw.js di browser belum terupdate / masih ngecache
- file manifest.json di browser belum terupdate / masih ngecache
6. cek di incognito
- file sw.js di browser belum terupdate / masih ngecache
- file manifest.json di browser berubah

**Gambar :** 
Percobaan di local : 
Gambar dari percobaan no 1, 2, 3
- file sw.js
![sw js](https://user-images.githubusercontent.com/40786221/42271166-d88e08ca-7fac-11e8-8f13-15e8dd42be4b.png)
- file manifest.json
![manifest json](https://user-images.githubusercontent.com/40786221/42271430-7fee7b0e-7fad-11e8-802a-030aaa96350e.png)

Gambar dari percobaan no 4
![update on load](https://user-images.githubusercontent.com/40786221/42271737-3d785c4e-7fae-11e8-8f7f-a7d520384729.png)

Gambar dari percobaan no 5
![manifest](https://user-images.githubusercontent.com/40786221/42271918-c2f5dc48-7fae-11e8-9511-2aa3e95b582f.png)
![sw](https://user-images.githubusercontent.com/40786221/42271920-c3320d30-7fae-11e8-9f14-cdd5d1602bc9.png)

Gambar dari percobaan no 6
![incognito](https://user-images.githubusercontent.com/40786221/42274072-8f9e6a20-7fb5-11e8-83cf-b031a347aaf3.png)

Percobaan di basic : 
Gambar dari percobaan no 1, 2, 3
- file sw.js
![basic sw](https://user-images.githubusercontent.com/40786221/42272401-2f60f7ae-7fb0-11e8-9a57-cda757e7680b.png)
- file manifest.json
![basic manifest](https://user-images.githubusercontent.com/40786221/42272652-1151a618-7fb1-11e8-957f-16816829e522.png)

Gambar dari percobaan no 4
![basic update](https://user-images.githubusercontent.com/40786221/42274166-e575416c-7fb5-11e8-973f-e7aef78d97ae.png)

Gambar dari percobaan no 5
![sw basic](https://user-images.githubusercontent.com/40786221/42274377-a486d520-7fb6-11e8-9860-58166c3f393c.png)

gambar dari percobaan no 6
![incognito basic](https://user-images.githubusercontent.com/40786221/42274561-59d2aea4-7fb7-11e8-9524-e5b56bf4b85c.png)

**Comment by todiadiyatmo** [comment]
![image](https://user-images.githubusercontent.com/2767210/42275260-e99847cc-7fb9-11e8-8880-d992bd8ff32b.png)

ini dilocal di buka di browser ngecache ? @irnanto27

**Comment by irnanto27** [comment]
iya mas @todiadiyatmo , sdh sy kasih gambarnya jg

**Comment by todiadiyatmo** [comment]
![image](https://user-images.githubusercontent.com/2767210/42298575-df23821c-8030-11e8-8af5-41dcb0d274a1.png)

setiap kali ngecek ctrl+f5 problem solving ga ?

**Comment by irnanto27** [comment]
tidak bisa keganti mas, sdh di ctrl+f5 (hard refresh). di alur proses uji coba saya sebutkan di nomor 4
