### ISSUE TITLE
Save harus men save semua opsi 

### ISSUE THREAD

**Issue by todiadiyatmo** [tonjoo/pwa-optimizer#5]
- [ ] ketika ditekan save semua opsi harus di save ulang bukan hanya di tab itu saja
- [ ] contoh : liat screenshoot
- [ ] ketika awal instalasi sudah ada default value yang terpasang dan di APPLY untuk setiap options : 
     - [ ] asset : enable, offline mode : disable , lazy load : enable, manifest kosong, add to homescreen : kosong

![image](https://user-images.githubusercontent.com/2767210/38654375-299c3abc-3e39-11e8-9373-fc4253f88fd9.png)

**Comment by ebenhaezerbm** [comment]
@todiadiyatmo opsi yang pertama option dirombak habis sih mas optionsnya, effort nya lumayan
solusi sementara sekarang saat pertama kali install sw.js nya (option offline dan cache) aku set ...
