### ISSUE TITLE
Bug on Options Page

### ISSUE THREAD

**Issue by todiadiyatmo** [tonjoo/pwa-optimizer#8]
Sample : 
screencast-o-matic.com/watch/cFfIlgDRqj

- [x] bagian offline mode kalau disave disable suka mbalik ke enable
- [x] bagian tab lain dicek satu2 apakah berubah nggak kalau disave terpisah , contoh cara cek nya ada di video. Sepertinya yang lazy load normal aku uda cek. yang 
- [x] kalau add to homescreen mati `manifest.json` -> searusnya tidak perlu ada

**Comment by ebenhaezerbm** [comment]
@todiadiyatmo 
1. done
2. done
3. codenya ada di `inc/manifest.class.php` line 40-48 file manifest tetap di render gak di hapus cuma gak di panggil
